### GET
GET http://localhost:3000/api/genres HTTP/1.1

### GET BY ID
GET http://localhost:3000/api/genres/68c1a2b5b58cb666743c132b HTTP/1.1

### POST
POST http://localhost:3000/api/genres HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY4YzdlMjcwZjBlYzY3YzA1MDg1YjZiYSIsImlhdCI6MTc1NzkzMDA5NiwiZXhwIjoxNzU3OTMzNjk2fQ.OlUSpID1C8jLtuERTAUqGjM-VTGO82PWm__hcyS_V2k

{
   "name" : "Sci-fi"
}

### PUT
PUT http://localhost:3000/api/genres/68c1a2b5b58cb666743c132b HTTP/1.1
Content-Type: application/json

{
"name": "Adventure"
}

### DELETE
DELETE http://localhost:3000/api/genres/68c1a2b5b58cb666743c132b HTTP/1.1
