### GET
GET http://localhost:3000/api/movies HTTP/1.1

### GET BY ID
GET http://localhost:3000/api/movies/68c2308476702946ac3c2d9a HTTP/1.1

### POST
POST http://localhost:3000/api/movies HTTP/1.1
Content-Type: application/json

 {
    "title":"Terminator",
    "genreId": "68c226afd5e25d361e4b7dcb",
    "numberInStock": 0,
    "dailyRentalRate": 0
 }
