### GET
GET http://localhost:3000/api/rentals HTTP/1.1


### GET BY ID
GET http://localhost:3000/api/rentals/ID_PLACE_HOLDER HTTP/1.1

### POST
POST http://localhost:3000/api/rentals
Content-Type: application/json

{
    "customerId" : "68c14bf8756e737890617d15",
    "movieId": "68c23fdad64eb44507cc5e29",
    "rentalFee":9
}