# GET
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "Reachers",
    "email": "macryaze@aiasacalodsaaaauad.csom",
    "password":"rzxq1314!!!!",
    "isAdmin": true
}